from enum import Enum, auto
from typing import Any, Literal, Protocol

import rich
from rich.box import Box
from rich.theme import Theme

from ...contract.cli import (
    CliDTO,
    LineDTO,
    MarkdownDTO,
    PanelDTO,
    RuleDTO,
    TableDTO,
)
from ...contract.external import RichRenderable
from ...contract.log import LogDTO
from ..color import ColorBox, Palette
from .boxes import Boxes


class Modus(Enum):
    RICH = auto()
    EMIT = auto()
    PRINT = auto()
    NULL = auto()


class Printer(Protocol):
    """
    Define the Interface for the Printer.

    - Type the implementation of the dynamically built instance

    """

    # TODO: super()

    # rich
    console: rich.Console
    _rich_theme: Theme

    # sstcore
    palette: Palette
    modus: Modus = Modus.RICH
    color_box: ColorBox
    _cb: ColorBox
    boxes: Boxes

    # meta
    project_name: str
    project_version: str

    @property
    def project_info(self) -> str: ...

    # base
    def load_theme(self, theme: dict[str, str] | None = None) -> None: ...
    def preview_themes(self) -> None: ...

    # core
    def __call__(self, target: Any, **kwargs) -> None: ...

    # essentials
    def color(self, text: str, color: str | None = None) -> str: ...
    def normalize(self, target: Any, **kwargs) -> str: ...
    def render(self, target: CliDTO, **kwargs) -> RichRenderable: ...
    #
    def render_panel(self, panel: PanelDTO) -> RichRenderable: ...
    def render_line(self, line: LineDTO) -> RichRenderable: ...
    def render_rule(self, rule: RuleDTO) -> RichRenderable: ...
    def render_table(self, table: TableDTO) -> RichRenderable: ...
    def render_markdown(self, markdown: MarkdownDTO) -> RichRenderable: ...
    def render_log(self, log: LogDTO) -> RichRenderable: ...

    # layout
    def panel(self, target: Any, **kwargs) -> None: ...
    # header
    def header(self, text: Any, frame: str = "cyan", **kwargs) -> None: ...
    def title(
        self, text: Any, title: str = "", title_align: str = "right", **kwargs
    ) -> None: ...
    def line(self, style: str = "") -> None: ...
    def lines(
        self,
        lines: list,
        style: str = "cyan",
        title: str | None = None,
        header: str | None = None,
    ) -> None: ...
    def lines_with_len(
        self, name: str, lines: list, style: str = "cyan"
    ) -> None: ...
    # box
    def box(self, target: Any, frame: str = "", box: Box = ...) -> None: ...
    def box_top(self, target: Any, frame: str = "") -> None: ...
    def box_bottom(self, target: Any, frame: str = "") -> None: ...
    def mini_box(
        self,
        target: Any,
        frame: str = "",
        mode: Literal["up", "down", "both"] = "both",
    ) -> None: ...
    def corner(self, target: Any, frame: str = "", box: Box = ...) -> None: ...

    def success(self, text: Any) -> None: ...
    def danger(self, text: Any) -> None: ...
    def warn(self, text: Any) -> None: ...
    def special(self, text: Any) -> None: ...
    def dip(self, head: Any, text: Any, color: str) -> None: ...

    def md(self, text: str, *args, header: int = 0, **kwargs) -> None: ...

    # Color shortcuts from ColorMixin
    def white(self, target: Any) -> None: ...
    def blue(self, target: Any) -> None: ...
    def red(self, target: Any) -> None: ...
    def green(self, target: Any) -> None: ...
    def cyan(self, target: Any) -> None: ...
    def magenta(self, target: Any) -> None: ...
    def yellow(self, target: Any) -> None: ...
    def black(self, target: Any) -> None: ...
