from typing import Any

class AnsiEmpty:
    @property
    def blue(self) -> AnsiColor: ...
    @property
    def green(self) -> AnsiColor: ...
    @property
    def red(self) -> AnsiColor: ...
    @property
    def bold(self) -> AnsiModifiers: ...
    @property
    def underline(self) -> AnsiModifiers: ...
    def __call__(self, text: str, color: Any) -> str: ...

class AnsiColor:
    @property
    def bold(self) -> AnsiColorModifiers: ...
    @property
    def underline(self) -> AnsiColorModifiers: ...
    def __call__(self, text: str, color: Any) -> str: ...

class AnsiModifiers:
    @property
    def blue(self) -> AnsiColorModifiers: ...
    @property
    def green(self) -> AnsiColorModifiers: ...
    @property
    def red(self) -> AnsiColorModifiers: ...
    def __call__(self, text: str, color: Any) -> str: ...

class AnsiColorModifiers:
    def __call__(self, text: str, color: Any) -> str: ...
