class PrinterEmpty:
    @property
    def red(self) -> PrinterColors: ...
    @property
    def green(self) -> PrinterColors: ...
    @property
    def blue(self) -> PrinterColors: ...
    @property
    def bold(self) -> PrinterModifiers: ...
    @property
    def underline(self) -> PrinterModifiers: ...
    def __call__(self, text: str) -> str: ...

class PrinterColors:
    @property
    def bold(self) -> PrinterColorsModifiers: ...
    @property
    def underline(self) -> PrinterColorsModifiers: ...
    def __call__(self, text: str) -> str: ...

class PrinterModifiers:
    @property
    def red(self) -> PrinterColorsModifiers: ...
    @property
    def green(self) -> PrinterColorsModifiers: ...
    @property
    def blue(self) -> PrinterColorsModifiers: ...
    def __call__(self, text: str) -> str: ...

class PrinterColorsModifiers:
    def __call__(self, text: str) -> str: ...
