class RandomEmpty:
    @property
    def key31(self) -> RandomFormatter: ...
    @property
    def key32(self) -> RandomFormatter: ...
    @property
    def key33(self) -> RandomFormatter: ...
    @property
    def key21(self) -> RandomGreeting: ...
    @property
    def key22(self) -> RandomGreeting: ...
    @property
    def key11(self) -> RandomRepeats: ...
    @property
    def key12(self) -> RandomRepeats: ...
    @property
    def key13(self) -> RandomRepeats: ...
    def __call__(self, target: str) -> str: ...

class RandomFormatter:
    @property
    def key21(self) -> RandomFormatterGreeting: ...
    @property
    def key22(self) -> RandomFormatterGreeting: ...
    @property
    def key11(self) -> RandomFormatterRepeats: ...
    @property
    def key12(self) -> RandomFormatterRepeats: ...
    @property
    def key13(self) -> RandomFormatterRepeats: ...
    def __call__(self, target: str) -> str: ...

class RandomGreeting:
    @property
    def key31(self) -> RandomFormatterGreeting: ...
    @property
    def key32(self) -> RandomFormatterGreeting: ...
    @property
    def key33(self) -> RandomFormatterGreeting: ...
    @property
    def key11(self) -> RandomGreetingRepeats: ...
    @property
    def key12(self) -> RandomGreetingRepeats: ...
    @property
    def key13(self) -> RandomGreetingRepeats: ...
    def __call__(self, target: str) -> str: ...

class RandomRepeats:
    @property
    def key31(self) -> RandomFormatterRepeats: ...
    @property
    def key32(self) -> RandomFormatterRepeats: ...
    @property
    def key33(self) -> RandomFormatterRepeats: ...
    @property
    def key21(self) -> RandomGreetingRepeats: ...
    @property
    def key22(self) -> RandomGreetingRepeats: ...
    def __call__(self, target: str) -> str: ...

class RandomFormatterGreeting:
    @property
    def key11(self) -> RandomFormatterGreetingRepeats: ...
    @property
    def key12(self) -> RandomFormatterGreetingRepeats: ...
    @property
    def key13(self) -> RandomFormatterGreetingRepeats: ...
    def __call__(self, target: str) -> str: ...

class RandomFormatterRepeats:
    @property
    def key21(self) -> RandomFormatterGreetingRepeats: ...
    @property
    def key22(self) -> RandomFormatterGreetingRepeats: ...
    def __call__(self, target: str) -> str: ...

class RandomGreetingRepeats:
    @property
    def key31(self) -> RandomFormatterGreetingRepeats: ...
    @property
    def key32(self) -> RandomFormatterGreetingRepeats: ...
    @property
    def key33(self) -> RandomFormatterGreetingRepeats: ...
    def __call__(self, target: str) -> str: ...

class RandomFormatterGreetingRepeats:
    def __call__(self, target: str) -> str: ...
