class GreeterEmpty:
    @property
    def key11(self) -> GreeterAttr1: ...
    @property
    def key12(self) -> GreeterAttr1: ...
    @property
    def key13(self) -> GreeterAttr1: ...
    @property
    def key21(self) -> GreeterAttr2: ...
    @property
    def key22(self) -> GreeterAttr2: ...
    @property
    def key31(self) -> GreeterAttr3: ...
    @property
    def key32(self) -> GreeterAttr3: ...
    @property
    def key33(self) -> GreeterAttr3: ...
    def __call__(self, text: str) -> str: ...

class GreeterAttr1:
    @property
    def key21(self) -> GreeterAttr1Attr2: ...
    @property
    def key22(self) -> GreeterAttr1Attr2: ...
    @property
    def key31(self) -> GreeterAttr1Attr3: ...
    @property
    def key32(self) -> GreeterAttr1Attr3: ...
    @property
    def key33(self) -> GreeterAttr1Attr3: ...
    def __call__(self, text: str) -> str: ...

class GreeterAttr2:
    @property
    def key11(self) -> GreeterAttr1Attr2: ...
    @property
    def key12(self) -> GreeterAttr1Attr2: ...
    @property
    def key13(self) -> GreeterAttr1Attr2: ...
    @property
    def key31(self) -> GreeterAttr2Attr3: ...
    @property
    def key32(self) -> GreeterAttr2Attr3: ...
    @property
    def key33(self) -> GreeterAttr2Attr3: ...
    def __call__(self, text: str) -> str: ...

class GreeterAttr3:
    @property
    def key11(self) -> GreeterAttr1Attr3: ...
    @property
    def key12(self) -> GreeterAttr1Attr3: ...
    @property
    def key13(self) -> GreeterAttr1Attr3: ...
    @property
    def key21(self) -> GreeterAttr2Attr3: ...
    @property
    def key22(self) -> GreeterAttr2Attr3: ...
    def __call__(self, text: str) -> str: ...

class GreeterAttr1Attr2:
    @property
    def key31(self) -> GreeterAttr1Attr2Attr3: ...
    @property
    def key32(self) -> GreeterAttr1Attr2Attr3: ...
    @property
    def key33(self) -> GreeterAttr1Attr2Attr3: ...
    def __call__(self, text: str) -> str: ...

class GreeterAttr1Attr3:
    @property
    def key21(self) -> GreeterAttr1Attr2Attr3: ...
    @property
    def key22(self) -> GreeterAttr1Attr2Attr3: ...
    def __call__(self, text: str) -> str: ...

class GreeterAttr2Attr3:
    @property
    def key11(self) -> GreeterAttr1Attr2Attr3: ...
    @property
    def key12(self) -> GreeterAttr1Attr2Attr3: ...
    @property
    def key13(self) -> GreeterAttr1Attr2Attr3: ...
    def __call__(self, text: str) -> str: ...

class GreeterAttr1Attr2Attr3:
    def __call__(self, text: str) -> str: ...
    pass
