class TextEmpty:
    @property
    def blue(self) -> TextColor: ...
    @property
    def green(self) -> TextColor: ...
    @property
    def red(self) -> TextColor: ...
    @property
    def repr(self) -> TextFormat: ...
    @property
    def title(self) -> TextFormat: ...
    @property
    def casefold(self) -> TextNormalize: ...
    @property
    def lower(self) -> TextNormalize: ...
    @property
    def nfc(self) -> TextNormalize: ...
    @property
    def upper(self) -> TextNormalize: ...
    @property
    def alnum(self) -> TextSanitize: ...
    @property
    def collapse(self) -> TextSanitize: ...
    @property
    def strip(self) -> TextSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColor:
    @property
    def repr(self) -> TextColorFormat: ...
    @property
    def title(self) -> TextColorFormat: ...
    @property
    def casefold(self) -> TextColorNormalize: ...
    @property
    def lower(self) -> TextColorNormalize: ...
    @property
    def nfc(self) -> TextColorNormalize: ...
    @property
    def upper(self) -> TextColorNormalize: ...
    @property
    def alnum(self) -> TextColorSanitize: ...
    @property
    def collapse(self) -> TextColorSanitize: ...
    @property
    def strip(self) -> TextColorSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextFormat:
    @property
    def blue(self) -> TextColorFormat: ...
    @property
    def green(self) -> TextColorFormat: ...
    @property
    def red(self) -> TextColorFormat: ...
    @property
    def casefold(self) -> TextFormatNormalize: ...
    @property
    def lower(self) -> TextFormatNormalize: ...
    @property
    def nfc(self) -> TextFormatNormalize: ...
    @property
    def upper(self) -> TextFormatNormalize: ...
    @property
    def alnum(self) -> TextFormatSanitize: ...
    @property
    def collapse(self) -> TextFormatSanitize: ...
    @property
    def strip(self) -> TextFormatSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextNormalize:
    @property
    def blue(self) -> TextColorNormalize: ...
    @property
    def green(self) -> TextColorNormalize: ...
    @property
    def red(self) -> TextColorNormalize: ...
    @property
    def repr(self) -> TextFormatNormalize: ...
    @property
    def title(self) -> TextFormatNormalize: ...
    @property
    def alnum(self) -> TextNormalizeSanitize: ...
    @property
    def collapse(self) -> TextNormalizeSanitize: ...
    @property
    def strip(self) -> TextNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextSanitize:
    @property
    def blue(self) -> TextColorSanitize: ...
    @property
    def green(self) -> TextColorSanitize: ...
    @property
    def red(self) -> TextColorSanitize: ...
    @property
    def repr(self) -> TextFormatSanitize: ...
    @property
    def title(self) -> TextFormatSanitize: ...
    @property
    def casefold(self) -> TextNormalizeSanitize: ...
    @property
    def lower(self) -> TextNormalizeSanitize: ...
    @property
    def nfc(self) -> TextNormalizeSanitize: ...
    @property
    def upper(self) -> TextNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColorFormat:
    @property
    def casefold(self) -> TextColorFormatNormalize: ...
    @property
    def lower(self) -> TextColorFormatNormalize: ...
    @property
    def nfc(self) -> TextColorFormatNormalize: ...
    @property
    def upper(self) -> TextColorFormatNormalize: ...
    @property
    def alnum(self) -> TextColorFormatSanitize: ...
    @property
    def collapse(self) -> TextColorFormatSanitize: ...
    @property
    def strip(self) -> TextColorFormatSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColorNormalize:
    @property
    def repr(self) -> TextColorFormatNormalize: ...
    @property
    def title(self) -> TextColorFormatNormalize: ...
    @property
    def alnum(self) -> TextColorNormalizeSanitize: ...
    @property
    def collapse(self) -> TextColorNormalizeSanitize: ...
    @property
    def strip(self) -> TextColorNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColorSanitize:
    @property
    def repr(self) -> TextColorFormatSanitize: ...
    @property
    def title(self) -> TextColorFormatSanitize: ...
    @property
    def casefold(self) -> TextColorNormalizeSanitize: ...
    @property
    def lower(self) -> TextColorNormalizeSanitize: ...
    @property
    def nfc(self) -> TextColorNormalizeSanitize: ...
    @property
    def upper(self) -> TextColorNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextFormatNormalize:
    @property
    def blue(self) -> TextColorFormatNormalize: ...
    @property
    def green(self) -> TextColorFormatNormalize: ...
    @property
    def red(self) -> TextColorFormatNormalize: ...
    @property
    def alnum(self) -> TextFormatNormalizeSanitize: ...
    @property
    def collapse(self) -> TextFormatNormalizeSanitize: ...
    @property
    def strip(self) -> TextFormatNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextFormatSanitize:
    @property
    def blue(self) -> TextColorFormatSanitize: ...
    @property
    def green(self) -> TextColorFormatSanitize: ...
    @property
    def red(self) -> TextColorFormatSanitize: ...
    @property
    def casefold(self) -> TextFormatNormalizeSanitize: ...
    @property
    def lower(self) -> TextFormatNormalizeSanitize: ...
    @property
    def nfc(self) -> TextFormatNormalizeSanitize: ...
    @property
    def upper(self) -> TextFormatNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextNormalizeSanitize:
    @property
    def blue(self) -> TextColorNormalizeSanitize: ...
    @property
    def green(self) -> TextColorNormalizeSanitize: ...
    @property
    def red(self) -> TextColorNormalizeSanitize: ...
    @property
    def repr(self) -> TextFormatNormalizeSanitize: ...
    @property
    def title(self) -> TextFormatNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColorFormatNormalize:
    @property
    def alnum(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def collapse(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def strip(self) -> TextColorFormatNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColorFormatSanitize:
    @property
    def casefold(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def lower(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def nfc(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def upper(self) -> TextColorFormatNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColorNormalizeSanitize:
    @property
    def repr(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def title(self) -> TextColorFormatNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextFormatNormalizeSanitize:
    @property
    def blue(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def green(self) -> TextColorFormatNormalizeSanitize: ...
    @property
    def red(self) -> TextColorFormatNormalizeSanitize: ...
    def __call__(self, text: str) -> str: ...

class TextColorFormatNormalizeSanitize:
    def __call__(self, text: str) -> str: ...
